import streamlit as st
from jamaibase import JamAI, types as t

# Main App
st.set_page_config(page_title="Permit Compliance Check", layout="wide")
st.title("Permit Compliance Check")
st.caption("A quick compliance check for Malaysian F&B owners. Find out if you are missing any required permits or licenses.")

# JamAI Configuration
PAT = st.secrets["PAT"]
PROJECT_ID = st.secrets["PROJECT_ID"]
ACTION_TABLE_ID = "PermitCheck" 
INPUT_COL = "Input"

jamai = JamAI(token=PAT, project_id=PROJECT_ID)

# Helper Functions
def classify_risk_level(business_info):
    operations = business_info["operations"]
    if "Serve Food" in operations or "Hire Foreign Workers" in operations:
        return "High"
    elif "Open New Branch" in operations:
        return "Medium"
    else:
        return "Low"

# Sidebar Controls
with st.sidebar:
    st.markdown(
        """
        <div style='text-align: center; color: grey; font-size: 12px;'>
            Kitchen Pilot © 2025 | By CodeFest2025 Hackathon Team AAA
        </div>
        """, 
        unsafe_allow_html=True
    )
    
# User Inputs 
col1, col2 = st.columns(2)

with col1:
    business_type = st.selectbox("Business Type", ["Restaurant", "Cafe", "Home-Bakery", "Food Stall", "Catering Service"])
    state = st.selectbox("State", ["Penang", "Kuala Lumpur", "Selangor", "Johor", "Other"])
    city = st.text_input("City")
    language = st.radio("Language Preference", ["English", "Malay"], horizontal=True)

with col2:
    employees = st.number_input("Number of Employees", min_value=1, step=1)
    operations = st.multiselect("Business Operations", ["Serve Food", "Deliver Food", "Hire Foreign Workers", "Open New Branch"])
    existing_permits = st.multiselect(
        "Existing Permits / Licenses",
        ["SSM Registration", "Food Handling License", "Halal Certification", "Local Council License"]
    )


# Submission Logic
if st.button("Check Compliance", type="primary"):
    if not city or not operations:
        st.warning("Please enter all required information.")
    else:
        # Prepare Data
        business_info = {
            "business_type": business_type,
            "state": state,
            "city": city,
            "operations": operations,
            "employees": employees,
            "existing_permits": existing_permits,
            "language": language
        }
        
        # Local Risk Calculation
        risk_level = classify_risk_level(business_info)
        
        # Compose text helpers
        ops_text = ", ".join(operations) if operations else "None"
        permits_text = ", ".join(existing_permits) if existing_permits else "None"
        
        # Compose sentence for AI
        sentence = (
            f"A {business_type} in {city}, {state}, operating: {ops_text}; "
            f"employees: {employees}; existing permits: {permits_text}; language: {language}."
        )

        st.divider()

        # UI TRANSLATION LOGIC
        if language == "Malay":
            t_input_summary = "Ringkasan Maklumat"
            t_analysis_result = "Keputusan Analisis"
            t_risk_assessment = "**Penilaian Risiko Awal:**"
            t_consulting = "Sedang merujuk Pangkalan Pengetahuan AI..."
            t_complete = "Analisis Selesai!"
            t_disclaimer = "⚠️ **Penafian:** Laporan ini dijana oleh Kepintaran Buatan (JamAI) untuk tujuan maklumat sahaja. Peraturan mungkin berubah. Sila sahkan semua keperluan dengan majlis tempatan (PBT) atau perunding bertauliah."
            t_download_label = "Muat Turun Laporan"
            
            # Risk Level Translation
            risk_map = {"High": "Tinggi", "Medium": "Sederhana", "Low": "Rendah"}
            display_risk = risk_map.get(risk_level, risk_level)
            
            # Headers
            header_permits = "### Senarai Permit Wajib"
            header_missing = "### Dokumen Yang Hilang"
            header_score = "### Skor Pematuhan"
        else:
            t_input_summary = "Business Summary"
            t_analysis_result = "Analysis Result"
            t_risk_assessment = "**Preliminary Risk Assessment:**"
            t_consulting = "Consulting AI Knowledge Base..."
            t_complete = "Analysis Complete!"
            t_disclaimer = "⚠️ **Disclaimer:** This report is generated by Artificial Intelligence (JamAI) for informational purposes only. Regulations may change. Please verify all requirements with your local council (PBT) or a certified consultant."
            t_download_label = "Download Report"
            
            # Risk Level (Keep English)
            display_risk = risk_level
            
            # Headers
            header_permits = "### Mandatory Permits List"
            header_missing = "### Missing Documents"
            header_score = "### Compliance Score"

        # DISPLAY INPUT SUMMARY BEFORE RESULTS
        st.subheader(t_input_summary)
        
        sum_col1, sum_col2 = st.columns(2)
        with sum_col1:
            st.write(f"**Business Type:** {business_type}")
            st.write(f"**Location:** {city}, {state}")
            st.write(f"**Employees:** {employees}")
        with sum_col2:
            st.write(f"**Operations:** {ops_text}")
            st.write(f"**Existing Permits:** {permits_text}")
            
        st.divider()

        # DISPLAY AI RESULTS 
        st.subheader(t_analysis_result)
        
        # Show local risk
        risk_color = "red" if risk_level == "High" else "orange" if risk_level == "Medium" else "green"
        st.markdown(f"{t_risk_assessment} :{risk_color}[{display_risk}]")
        
        with st.status(t_consulting, expanded=True) as status:
            # Push to JamAI Action table
            if PROJECT_ID and PAT and ACTION_TABLE_ID and INPUT_COL:
                try:
                    client = JamAI(project_id=PROJECT_ID, token=PAT)
                    req = t.MultiRowAddRequest(
                        table_id=ACTION_TABLE_ID,
                        data=[{INPUT_COL: sentence}],
                        stream=False,
                    )
                
                    res = client.table.add_table_rows(t.TableType.ACTION, req)
                    
                    if res.rows and len(res.rows) > 0:
                        # Translated completion text
                        status.update(label=t_complete, state="complete", expanded=False)
                        
                        # Extract the row data
                        row_data = res.rows[0].columns
                        
                        # Helper to safely get text
                        def get_text(key):
                            val = row_data.get(key)
                            if hasattr(val, "text"): return val.text
                            return str(val) if val else "N/A"

                        # Required Permits
                        st.markdown(header_permits)
                        val_required = get_text("Output") 
                        if val_required == "N/A": val_required = get_text("required_permits")
                        st.info(val_required)

                        # Missing Permits & Score
                        col_a, col_b = st.columns(2)
                        
                        with col_a:
                            st.markdown(header_missing)
                            val_missing = get_text("Comparison")
                            if val_missing == "N/A": val_missing = get_text("missing_permits")
                            st.warning(val_missing)
                        
                        with col_b:
                            st.markdown(header_score)
                            val_score = get_text("CalScore")
                            if val_score == "N/A": val_score = get_text("score")
                            st.success(val_score)
                        
                        # AI DISCLAIMER
                        st.caption(t_disclaimer)

                        # DOWNLOAD BUTTON LOGIC 
                        st.divider()
                        
                        # Build the text file content
                        report_content = (
                            f"=== {t_input_summary.upper()} ===\n"
                            f"Business: {business_type}\n"
                            f"Location: {city}, {state}\n"
                            f"Employees: {employees}\n"
                            f"Operations: {ops_text}\n"
                            f"Existing Permits: {permits_text}\n\n"
                            f"=== {t_analysis_result.upper()} ===\n"
                            f"Risk Assessment: {display_risk}\n\n"
                            f"{header_permits.replace('#', '').strip()}\n"
                            f"{'-'*30}\n"
                            f"{val_required}\n\n"
                            f"{header_missing.replace('#', '').strip()}\n"
                            f"{'-'*30}\n"
                            f"{val_missing}\n\n"
                            f"{header_score.replace('#', '').strip()}\n"
                            f"{'-'*30}\n"
                            f"{val_score}\n\n"
                            f"==============================\n"
                            f"{t_disclaimer.replace('**', '')}"
                        )

                        # Render the button
                        st.download_button(
                            label=t_download_label,
                            data=report_content,
                            file_name=f"Compliance_Report_{city}_{business_type}.txt",
                            mime="text/plain"
                        )
                            
                    else:
                        status.update(label="No response received from AI.", state="error")
                        st.error("The Action Table did not return any rows.")
                        
                except Exception as e:
                    status.update(label="Connection Failed", state="error")
                    st.error(f"Error communicating with JamAI: {e}")
            else:
                st.warning("Configuration missing. Please check Project ID, PAT, and Table ID.")